/**
 * Seed script — populates MockAPI with 13 realistic blog posts.
 * Run once: node scripts/seed-mockapi.mjs
 */
const API = 'https://6a3e7d4e0443193a1a0bf936.mockapi.io/api/blog/posts';

const posts = [
  {
    title: 'Mastering Next.js 14 App Router: The Complete Guide',
    description: 'A deep dive into Next.js 14 App Router, Server Components, and new data-fetching paradigms that are changing how we build React applications.',
    content: '<p>Next.js 14 represents a fundamental shift in how we think about React applications. The App Router, built on React Server Components, enables a new architecture where components render on the server by default.</p><h2>Server Components vs Client Components</h2><p>Server Components run exclusively on the server, have zero bundle impact, and can directly access databases and APIs. Client Components, marked with "use client", handle interactivity in the browser.</p><h2>Data Fetching Simplified</h2><p>Gone are the days of getServerSideProps. In the App Router, any async Server Component can fetch data directly — co-locating data fetching with the component that needs it.</p><h2>Streaming and Suspense</h2><p>Next.js 14 enables streaming HTML from the server, progressively rendering UI as data becomes available. Combined with Suspense, you can show loading skeletons without blocking the entire page.</p>',
    coverImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&h=675&fit=crop',
    category: 'Programming',
    author: 'James Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-06-15',
    readingTime: 12,
    likes: 4823,
    views: 21400,
    tags: ['nextjs', 'react', 'web development', 'javascript'],
    featured: true,
    trending: true,
  },
  {
    title: 'React 19: New Hooks and Concurrent Features Explained',
    description: 'Explore transformative features in React 19 including the use() hook, Actions, optimistic updates, and how they simplify state management.',
    content: '<p>React 19 ships with features that address the most common pain points developers face. From simplified data fetching to built-in optimistic UI patterns, this release is a major leap forward.</p><h2>The use() Hook</h2><p>The new use() hook reads the value of a Promise or Context during render. Unlike useEffect, use() can be called conditionally and integrates with Suspense automatically.</p><h2>React Actions</h2><p>Actions replace manual loading and error state management when submitting forms. React automatically handles the pending state for async form actions.</p><h2>useOptimistic</h2><p>Show a different state while an async action is in progress. When the action completes, React reverts to the actual state — making snappy UIs trivially simple.</p>',
    coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&h=675&fit=crop',
    category: 'Programming',
    author: 'James Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-06-10',
    readingTime: 10,
    likes: 3912,
    views: 17800,
    tags: ['react', 'javascript', 'hooks', 'web development'],
    featured: false,
    trending: true,
  },
  {
    title: 'TypeScript 5.5 Advanced Patterns for Modern Development',
    description: 'Master the latest TypeScript features and advanced patterns that will elevate your code quality and developer experience.',
    content: '<p>TypeScript 5.5 introduces powerful features that make type-safe development more intuitive. From improved type inference to new utility types, these features transform how we write JavaScript applications.</p><h2>Inferred Type Predicates</h2><p>TypeScript 5.5 automatically narrows types based on control flow, eliminating explicit type guards in many cases. This makes filtering arrays and narrowing unions more ergonomic.</p><h2>const Type Parameters</h2><p>Preserve literal types in generic functions, making it easier to create APIs that work with literal values without sacrificing type safety.</p><h2>Decorator Metadata</h2><p>With the new decorator metadata API, TypeScript supports the TC39 stage 3 decorator proposal, enabling more powerful and interoperable decorators.</p>',
    coverImage: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=1200&h=675&fit=crop',
    category: 'Programming',
    author: 'James Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-05-20',
    readingTime: 8,
    likes: 2134,
    views: 9200,
    tags: ['typescript', 'javascript', 'programming', 'web development'],
    featured: false,
    trending: false,
  },
  {
    title: 'Tailwind CSS v4: Everything You Need to Know',
    description: 'Tailwind CSS v4 rewrites the engine in Rust, drops the config file, and adds native CSS variables support. Here is what changes for your workflow.',
    content: '<p>Tailwind CSS v4 is the most significant update since the project launched. A complete rewrite of the engine in Rust delivers 10x faster build times and a fundamentally simpler configuration model.</p><h2>No More Config File</h2><p>Tailwind v4 uses CSS itself as the configuration file. You define your design tokens directly in CSS using custom properties, making the setup more intuitive and portable.</p><h2>Native CSS Variables</h2><p>Every design token is now a CSS custom property by default. This means your Tailwind colors, spacing, and typography values are accessible throughout your stylesheet.</p><h2>Lightning CSS</h2><p>The new engine uses Lightning CSS for transforms, vendor prefixing, and syntax lowering — eliminating the need for separate PostCSS plugins in most projects.</p>',
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&h=675&fit=crop',
    category: 'Programming',
    author: 'Sarah Mitchell',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-06-08',
    readingTime: 7,
    likes: 3241,
    views: 14600,
    tags: ['tailwindcss', 'css', 'web development', 'design'],
    featured: false,
    trending: true,
  },
  {
    title: 'Generative AI: Beyond ChatGPT to the Creative Revolution',
    description: 'Discover how generative AI is reshaping creative industries and what it means for artists, writers, and developers in 2025.',
    content: '<p>Generative AI has moved beyond novelty to become a transformative force across creative industries. From image generation to code completion, these tools are redefining what it means to create.</p><h2>The Creative Renaissance</h2><p>Artists are embracing AI as a collaborative partner. The ability to iterate through hundreds of variations in minutes has opened new creative possibilities that were simply impossible before.</p><h2>Implications for Developers</h2><p>For software developers, AI coding assistants have become indispensable. Studies show 30-40% faster development cycles with AI pair programming tools.</p><h2>Ethical Considerations</h2><p>The rapid adoption of generative AI raises important questions about copyright, attribution, and the future of creative work. New frameworks for intellectual property are urgently needed.</p>',
    coverImage: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=675&fit=crop',
    category: 'Artificial Intelligence',
    author: 'James Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-06-12',
    readingTime: 6,
    likes: 2856,
    views: 9800,
    tags: ['ai', 'generative', 'creativity', 'machine learning'],
    featured: true,
    trending: true,
  },
  {
    title: 'Building Production RAG Systems with LangChain and Next.js',
    description: 'A practical guide to building retrieval-augmented generation systems that power real AI applications, end-to-end from embeddings to streaming UI.',
    content: '<p>Retrieval-Augmented Generation (RAG) is the dominant architecture for production AI applications. It solves the hallucination problem by grounding LLM responses in your own data.</p><h2>The RAG Pipeline</h2><p>A RAG system has three stages: ingestion (chunk and embed your documents), retrieval (find relevant chunks via vector similarity), and generation (pass context to the LLM with the user query).</p><h2>LangChain Integration</h2><p>LangChain provides the orchestration layer that connects your vector store, embedding model, and LLM into a coherent pipeline. The new LangChain Expression Language (LCEL) makes composition clean and type-safe.</p><h2>Streaming with Next.js</h2><p>Use the Vercel AI SDK with Next.js route handlers to stream LLM responses directly to your UI. Users see tokens appear in real-time rather than waiting for the full response.</p>',
    coverImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&h=675&fit=crop',
    category: 'Artificial Intelligence',
    author: 'James Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-05-28',
    readingTime: 14,
    likes: 1987,
    views: 8400,
    tags: ['ai', 'rag', 'langchain', 'nextjs'],
    featured: false,
    trending: false,
  },
  {
    title: 'The Future of UI Design: From Flat to Spatial Computing',
    description: 'How spatial computing and AR/VR are transforming the way we design digital interfaces and user experiences beyond the screen.',
    content: '<p>User interface design is undergoing its most significant transformation since the shift from skeuomorphism to flat design. Spatial computing is creating entirely new paradigms for human-computer interaction.</p><h2>Designing for 3D Space</h2><p>Traditional 2D screen constraints are replaced by three-dimensional freedom. Designers now consider depth, proximity, gaze, and gesture as primary interaction methods.</p><h2>The Apple Vision Pro Effect</h2><p>Apple Vision Pro represents a watershed moment. The spatial computing interface demonstrates how familiar 2D apps must evolve when the canvas becomes the entire physical space around you.</p><h2>The New Design Toolkit</h2><p>Spline, Bezi, and Unity are becoming essential tools alongside Figma. Prototyping in 3D demands a different mindset — one that prioritizes natural movement and intuitive gestures over pixel precision.</p>',
    coverImage: 'https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=1200&h=675&fit=crop',
    category: 'Design',
    author: 'Alexandra Kim',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-06-05',
    readingTime: 9,
    likes: 2345,
    views: 8900,
    tags: ['design', 'spatial', 'ar', 'vr', 'ui'],
    featured: true,
    trending: false,
  },
  {
    title: 'Design Systems at Scale: Lessons from Building Component Libraries',
    description: 'Hard-won lessons from maintaining design systems used by hundreds of developers — from token architecture to versioning strategies.',
    content: '<p>Building a design system is easy. Maintaining one that scales across dozens of teams and hundreds of components is genuinely hard. Here is what we learned.</p><h2>Token Architecture First</h2><p>Start with your design token hierarchy before writing a single component. Primitive tokens (exact values), semantic tokens (purpose-based aliases), and component tokens form the backbone of a maintainable system.</p><h2>Versioning Without Breaking Teams</h2><p>Semantic versioning is table stakes. What matters more is your migration strategy. Codemods, deprecation warnings, and migration guides reduce the cost of major version upgrades dramatically.</p><h2>The Documentation Trap</h2><p>Most design systems fail from insufficient documentation, not bad components. Invest in living documentation — Storybook with interaction tests, Figma annotations, and real usage examples.</p>',
    coverImage: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&h=675&fit=crop',
    category: 'Design',
    author: 'Alexandra Kim',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-05-15',
    readingTime: 11,
    likes: 1876,
    views: 7300,
    tags: ['design', 'design systems', 'component library', 'ui'],
    featured: false,
    trending: false,
  },
  {
    title: 'The Science of Deep Work: Optimizing Your Cognitive Performance',
    description: 'Evidence-based strategies to reach peak cognitive performance, eliminate distractions, and produce your best work consistently.',
    content: '<p>Deep work — the ability to focus without distraction on cognitively demanding tasks — is becoming increasingly rare and increasingly valuable. Cal Newport argues it may be the superpower of the 21st century.</p><h2>The Neuroscience of Focus</h2><p>When you focus deeply, the brain enters a state of heightened activity in the prefrontal cortex. Myelin builds around frequently used neural circuits, making these pathways faster and more efficient over time.</p><h2>Structuring Your Deep Work</h2><p>The monastic philosophy works for writers and researchers with full schedule control. For knowledge workers, time-blocking — scheduling specific deep work blocks in your calendar — delivers most of the benefits.</p><h2>Eliminating the Distraction Trap</h2><p>Every context switch costs approximately 23 minutes of recovery time, per research from UC Irvine. Batching shallow work and protecting your deep work blocks is not optional — it is essential.</p>',
    coverImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=1200&h=675&fit=crop',
    category: 'Lifestyle',
    author: 'Emily Rodriguez',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-05-22',
    readingTime: 8,
    likes: 4123,
    views: 18200,
    tags: ['productivity', 'lifestyle', 'focus', 'work'],
    featured: false,
    trending: true,
  },
  {
    title: 'Southeast Asia Hidden Gems: Off the Beaten Path in 2025',
    description: 'Beyond Bali and Bangkok — the underrated destinations offering authentic experiences without the tourist crowds.',
    content: '<p>Southeast Asia beyond the icons rewards patient travelers. Kampot, Koh Rong Samloem, the Kei Islands, and Phongsaly Province offer experiences that the tourist trail has not yet homogenized.</p><h2>Kampot, Cambodia</h2><p>A riverside colonial town with the best pepper in the world, stunning Bokor Mountain, and a genuine arts community that has grown organically rather than for tourists.</p><h2>Kei Islands, Indonesia</h2><p>Part of the Maluku province, these islands have beaches that rival the Maldives without the price tag or crowds. The diving is world-class and largely undiscovered.</p><h2>Phongsaly, Laos</h2><p>Northern Laos most remote province. Dozens of ethnic minority villages, centuries-old tea trees, and trekking that genuinely immerses you in traditional life.</p>',
    coverImage: 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=1200&h=675&fit=crop',
    category: 'Travel',
    author: 'Emily Rodriguez',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-06-03',
    readingTime: 5,
    likes: 3156,
    views: 11200,
    tags: ['travel', 'southeast asia', 'adventure', 'culture'],
    featured: false,
    trending: false,
  },
  {
    title: 'The Science of Sleep: Evidence-Based Strategies for Peak Recovery',
    description: 'What the research actually says about sleep optimization — and the practical changes that make the biggest difference.',
    content: '<p>Sleep is not merely rest. It is an active biological process where the brain consolidates memories, clears metabolic waste, and repairs tissue. Shortchanging it has measurable, compounding costs.</p><h2>Sleep Architecture Matters</h2><p>A complete sleep cycle — N1, N2, N3 deep sleep, and REM — takes approximately 90 minutes. Deep sleep dominates early in the night; REM dominates later. Both serve distinct, irreplaceable functions.</p><h2>Circadian Rhythm Alignment</h2><p>Morning light exposure within 30 minutes of waking is the single most powerful lever for setting your circadian rhythm. It advances your sleep timing, improves mood, and increases afternoon alertness.</p><h2>The 10-3-2-1-0 Rule</h2><p>No caffeine 10 hours before bed, no food 3 hours before, no work 2 hours before, no screens 1 hour before, and 0 snooze presses. Simple rules, dramatic results.</p>',
    coverImage: 'https://images.unsplash.com/photo-1541781777631-fa182f0c6d6d?w=1200&h=675&fit=crop',
    category: 'Health',
    author: 'David Thompson',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-06-01',
    readingTime: 10,
    likes: 5234,
    views: 23100,
    tags: ['sleep', 'health', 'wellness', 'performance'],
    featured: false,
    trending: true,
  },
  {
    title: 'Sustainable Business Models: How Companies Are Profiting from Purpose',
    description: 'The shift from ESG as compliance to ESG as competitive advantage — case studies from companies making sustainability core to their strategy.',
    content: '<p>Sustainability is no longer a cost center or PR exercise. The most sophisticated companies have figured out how to make environmental responsibility a source of competitive advantage and genuine profitability.</p><h2>The Circular Economy Advantage</h2><p>Patagonia Worn Wear, IKEA buyback, and Renault remanufacturing show that keeping products in use longer reduces input costs, builds loyalty, and creates entirely new revenue streams.</p><h2>ESG as Performance Signal</h2><p>Studies consistently show ESG leaders outperform their peers over 5+ year horizons. The mechanism is simple: companies that manage environmental and social risks well also tend to manage operational risks well.</p><h2>Consumer-Driven Change</h2><p>73% of global consumers say they would change habits to reduce environmental impact. This is not idealism — it is a massive market signal that forward-thinking brands are capturing.</p>',
    coverImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&h=675&fit=crop',
    category: 'Business',
    author: 'Michael Park',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-06-08',
    readingTime: 7,
    likes: 1890,
    views: 7600,
    tags: ['sustainability', 'business', 'esg', 'strategy'],
    featured: false,
    trending: true,
  },
  {
    title: 'AI-Powered Personalized Learning: The End of One-Size-Fits-All Education',
    description: 'How adaptive AI tutors are democratizing access to expert-level education and what it means for the future of schools.',
    content: '<p>Education is undergoing a fundamental transformation as artificial intelligence enables truly personalized learning. The one-size-fits-all approach is giving way to adaptive systems that respond to each learner.</p><h2>Adaptive Learning in Practice</h2><p>Khan Academy Khanmigo, Duolingo Max, and Carnegie Learning demonstrate that AI can identify exactly where a student is struggling and adjust instruction in real time — something no human teacher can do at scale.</p><h2>Democratizing Expert Tutoring</h2><p>Research shows one-on-one tutoring produces a 2-sigma improvement in student outcomes over classroom instruction. AI tutors can deliver personalized attention at essentially zero marginal cost.</p><h2>The Teacher Evolution</h2><p>Rather than replacing teachers, AI handles the repetitive aspects — grading, assessment, content delivery — freeing teachers to focus on mentorship, motivation, and the human dimensions of learning.</p>',
    coverImage: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&h=675&fit=crop',
    category: 'Education',
    author: 'Olivia Wang',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
    publishDate: '2025-05-28',
    readingTime: 7,
    likes: 2789,
    views: 10400,
    tags: ['education', 'ai', 'learning', 'technology'],
    featured: false,
    trending: false,
  },
];

async function seed() {
  const existing = await fetch(API).then(r => r.json());
  if (existing.length > 0) {
    console.log(`MockAPI already has ${existing.length} posts. Skipping.`);
    return;
  }
  let created = 0;
  for (const post of posts) {
    const res = await fetch(API, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(post),
    });
    if (res.ok) {
      created++;
      console.log(`✓ [${created}/${posts.length}] ${post.title.substring(0, 60)}`);
    } else {
      console.error(`✗ Failed: ${res.status} ${await res.text()}`);
    }
    await new Promise(r => setTimeout(r, 300));
  }
  console.log(`\nSeeded ${created} posts.`);
}

seed().catch(console.error);
